#!/usr/bin/env bash

(
  mkdir -p ~/code/vimplugins
  cd ~/code/vimplugins
  grep "Plug '~" ~/vimrc/plugins.vim | sed "s_.*code/vimplugins/\([^']*\)'_\1_" | xargs -I{} git clone git@github.com:TamaMcGlinn/{}
)
