#!/bin/bash

(
  # Install vimrc
  cd ~
  git clone git@github.com:TamaMcGlinn/vimrc.git
  mkdir -p ~/.config/nvim
  ln -fs ~/vimrc/vimrc.vim ~/.config/nvim/init.vim

  rm -rf ~/.config/nvim/UltiSnips
  ln -s ~/vimrc/UltiSnips ~/.config/nvim/UltiSnips
)
