#!/bin/bash

# General stuff, including the requirements to build neovim
sudo apt-get install -y curl make xclip git build-essential clang libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl exuberant-ctags cscope vim gparted pastebinit tree cgdb ruby silversearcher-ag lua5.3 gettext ninja-build subversion virtualenv python3.8-dev rubygems ruby-dev graphviz vlc python3-venv shellcheck libboost-dev cargo neovim python3-pip libx11-dev byzanz exfat-fuse ruby python2 ripgrep ssh-askpass xournal net-tools tmux nnn git-review npm rename

# vim-bible requirements
sudo apt-get install -y diatheke sword-text-dutsvv sword-text-kjv

read -r -p "
Install neomutt and abook for email?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  custom_installers/email
fi

mkdir ~/code

custom_installers/get_xrectsel

# turn off terminal bell
dconf write /org/gnome/desktop/sound/event-sounds "false"

custom_installers/get_fzf
custom_installers/get_neovim
custom_installers/get_alire
custom_installers/forgit
custom_installers/install_treesitter
custom_installers/install_langservers
custom_installers/mkproj

# install markdownfmt https://github.com/tianon/markdownfmt
go install github.com/tianon/markdownfmt@latest

read -r -p "
Install wemux?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  custom_installers/wemux
fi


install_vimrc

read -r -p "
Install private vimrc?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  ./install_private_vimrc
fi

# Install nerdfont
mkdir -p ~/.local/share/fonts
cp 'nerdfont/Ubuntu Mono Nerd Font Complete Mono.ttf' ~/.local/share/fonts/

./install_config_symlinks
