#!/bin/bash

# General stuff, including the requirements to build neovim
sudo apt-get install curl make xclip git build-essential clang libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl exuberant-ctags cscope vim python gparted pastebinit tree cgdb ruby silversearcher-ag lua5.3 gettext ninja-build subversion virtualenv python-dev python3.8-dev rubygems ruby-dev graphviz vlc python3-venv shellcheck libboost-dev cargo neovim python3-pip libx11-dev byzanz exfat-fuse exfat-utils ruby python2 exa ripgrep ssh-askpass xournal net-tools tmux nnn

mkdir ~/code
custom_installers/get_xrectsel

# turn off terminal bell
dconf write /org/gnome/desktop/sound/event-sounds "false"

custom_installers/get_fzf
custom_installers/get_neovim
custom_installers/get_alire
custom_installers/forgit

# Install nerdfont
mkdir -p ~/.local/share/fonts
cp 'nerdfont/Ubuntu Mono Nerd Font Complete Mono.ttf' ~/.local/share/fonts/

