#!/bin/bash

# General stuff, including the requirements to build neovim
sudo apt-get install -y curl make xclip git build-essential clang libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl exuberant-ctags cscope vim gparted pastebinit tree cgdb ruby silversearcher-ag lua5.3 gettext ninja-build subversion virtualenv python3.8-dev rubygems ruby-dev graphviz vlc python3-venv shellcheck libboost-dev cargo neovim python3-pip libx11-dev byzanz exfat-fuse ruby python2 ripgrep ssh-askpass xournal net-tools tmux nnn git-review rename fd-find gifsicle freerdp2-x11

# update nodejs
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -
sudo apt-get install -y nodejs

# Go needs snap install to support installing things
sudo snap install go --classic

pip3 install trash-cli gita openai

# vim-bible requirements
sudo apt-get install -y diatheke sword-text-dutsvv sword-text-kjv

read -r -p "
Install neomutt and abook for email?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  custom_installers/email
fi

mkdir ~/code

custom_installers/get_xrectsel

# turn off terminal bell
dconf write /org/gnome/desktop/sound/event-sounds "false"

custom_installers/get_fzf
custom_installers/get_neovim
custom_installers/get_alire
custom_installers/forgit
custom_installers/install_treesitter
custom_installers/install_langservers
custom_installers/mkproj

# install markdownfmt https://github.com/tianon/markdownfmt
go install github.com/tianon/markdownfmt@latest

# install buildifier
# go install github.com/bazelbuild/buildtools/buildifier@latest
wget https://github.com/bazelbuild/buildtools/releases/download/5.1.0/buildifier-linux-amd64
mv buildifier-linux-amd64 linuxbash/buildifier
chmod +x linuxbash/buildifier

# lua formatters
custom_installers/install_luarocks
sudo luarocks install --server=https://luarocks.org/dev luaformatter
custom_installers/install_lua_language_server

# install docker
sudo snap install docker

# install git-delta
cargo install git-delta

read -r -p "
Install wemux?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  custom_installers/install_wemux
fi


install_vimrc

read -r -p "
Install private vimrc?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  ./install_private_vimrc
fi

# Install nerdfont
mkdir -p ~/.local/share/fonts
wget 'https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/UbuntuMono.zip' && unzip UbuntuMono.zip && mv UbuntuMono*.ttf ~/.local/share/fonts/ && rm LICENCE.txt LICENCE-FAQ.txt README.md UbuntuMono.zip 

./install_config_symlinks

# cleanup
rm -rf luarocks-3.8.0* lua-*.tar.gz package.json yarn.lock
