#!/bin/bash

read -r -p "
Install neomutt and abook for email?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  custom_installers/email
fi

# General stuff, including the requirements to build neovim
sudo apt-get install curl make xclip git build-essential clang libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl exuberant-ctags cscope vim python gparted pastebinit tree cgdb ruby silversearcher-ag lua5.3 gettext ninja-build subversion virtualenv python-dev python3.8-dev rubygems ruby-dev graphviz vlc python3-venv shellcheck libboost-dev cargo neovim python3-pip libx11-dev byzanz exfat-fuse exfat-utils ruby python2 exa ripgrep ssh-askpass xournal net-tools tmux nnn git-review ripgrep

mkdir ~/code

custom_installers/get_xrectsel

# turn off terminal bell
dconf write /org/gnome/desktop/sound/event-sounds "false"

custom_installers/get_fzf
custom_installers/get_neovim
custom_installers/get_alire
custom_installers/forgit
custom_installers/install_treesitter
custom_installers/install_langservers

read -r -p "
Install wemux?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  custom_installers/wemux
fi


install_vimrc

read -r -p "
Install private vimrc?
[y/n]: " response

if [[ "$response" = "y" ]]
then
  install_private_vimrc
fi

# Install nerdfont
mkdir -p ~/.local/share/fonts
cp 'nerdfont/Ubuntu Mono Nerd Font Complete Mono.ttf' ~/.local/share/fonts/

install_config_symlinks
