#!/bin/bash

ln -fs ~/dotfiles/bash_aliases ~/.bash_aliases
ln -fs ~/dotfiles/shellcheckrc ~/.shellcheckrc
mkdir -p ~/.config/gtk-3.0/
ln -fs ~/dotfiles/gtk-config.css ~/.config/gtk-3.0/gtk.css
ln -fs ~/dotfiles/bashrc ~/.bashrc
ln -fs ~/dotfiles/gitconfig ~/.gitconfig
ln -fs ~/dotfiles/tigrc ~/.tigrc
mkdir -p ~/.config/kitty/
ln -fs ~/dotfiles/kitty.conf ~/.config/kitty/kitty.conf
ln -fs ~/dotfiles/tmux.conf ~/.tmux.conf
ln -fs ~/dotfiles/muttrc/muttrc.muttrc ~/.muttrc
ln -fs ~/dotfiles/cookiecutterrc ~/.cookiecutterrc
