#!/bin/bash
# General stuff, including the requirements to build neovim
sudo apt-get install xclip git build-essential clang libtool libtool-bin autoconf automake cmake g++ pkg-config unzip icedove curl exuberant-ctags cscope vim python gparted pastebinit tree cgdb ruby silversearcher-ag libsdl1.2-dev libsdl2-dev lua5.3 gettext ninja-build subversion nodejs npm virtualenv python-dev ipython python3.8-dev texlive-latex-base libgtk-3-dev wine-stable

dconf write /org/gnome/desktop/sound/event-sounds "false"

# Build NeoVim from source
mkdir -p ~/code
git clone https://github.com/neovim/neovim.git ~/code/neovim
cd ~/code/neovim
make
sudo make install

# Get dein
~/dotfiles/custom_installers/get_dein

# Get trash-put
~/dotfiles/custom_installers/get_tp

# Get fzf
~/dotfiles/custom_installers/get_fzf
