#!/usr/bin/env bash

OUTPUT_FILE=${1-concatenated_videos.mp4}
find . -maxdepth 1 -type f -iname '*.mp4' | sed 's@^\./\(.*\)$@file '\''\1'\''@' > concat_videos_inputs.txt
ffmpeg -f concat -i concat_videos_inputs.txt -vcodec libx265 -crf 35 "$OUTPUT_FILE"
rm concat_videos_inputs.txt

