#!/bin/bash

# Outputs the chat lines from a source game's console.log file
# If given parameters, these are passed to grep; if it matches, 
# you get a notification of the message

LOGFILE=~/.steam/steam/steamapps/common/Empires/empires/console.log
tail -f $LOGFILE | (while read line; do 
	echo $line | grep "([^)]*)\ [^:]*:\ .*" -o; if [ $? -eq 1 ]; then continue; fi; 
	if (( $# == 0 )); then continue; fi;
	echo $line | grep $@ > /dev/null; 
	if [ $? -eq 0 ]; then 
		NAME=`echo $line | sed 's/.*([^)]*)\ \([^:]*\):.*/\1/'`; 
		MSG=`echo $line | sed 's/.*([^)]*)\ [^:]*:\ \(.*\)/\1/'`;
		notify-send "$NAME" "$MSG" --icon=dialog-information; 
	fi;
done)
