#!/usr/bin/env python3

import argparse
import re

parser = argparse.ArgumentParser()
parser.add_argument("file")
args = parser.parse_args()

namespace_regex = re.compile(r"^namespace ([^_]*)$")
namespaces = []

with open(args.file) as file:
    for line in file:
        match = re.search(namespace_regex, line)
        if match:
            namespace = match.group(1).replace("\n", "")
            namespaces.append(namespace)

print("::".join(namespaces))
