#!/usr/bin/env bash

# Original reason for the script: gcc (and gprbuild) output only the filename,
# not the full path as required by efm-langserver
FULLPATH=$(readlink -f "$1")
FILE_NAME=${FULLPATH##*/}

# Find *.gpr upwards from source file
# TODO allow overriding GPRFILE from neovim, for multi-gpr projects - in that case, do not search
DIR=$(dirname "$FULLPATH")
while
  GPRFILE=$(find "$DIR"/ -maxdepth 1 -type f -iname "*.gpr")
  [[ -z $GPRFILE ]] && [[ "$DIR" != "/" ]]
do DIR=$(dirname "$DIR"); done

if [[ -n $GPRFILE ]]; then
  PROJECT="-P $GPRFILE"
fi

COMMAND="gnatprove ${PROJECT}"
$COMMAND 2>&1 | sed "s@${FILE_NAME}@${FULLPATH}@"

# Debugging line to get info directly from linter into file
# echo "src/two.adb:03:00: Note: yes ${COMMAND}"


# To use this script, use efm-langserver https://github.com/mattn/efm-langserver
# and a NeoVim LSP configuration such as:
#
# require"lspconfig".efm.setup {
#     init_options = {documentFormatting = true},
#     settings = {
#         rootMarkers = {".git/"},
#         languages = {
#             ada = {
#                 {
#                     lintCommand = 'gnatprove_lint',
#                     lintIgnoreExitCode = true,
#                     lintFormats = {
#                         '%f:%l:%c: %trror: %m', '%f:%l:%c: %tarning: %m',
#                         '%f:%l:%c: %tote: %m'
#                     }
#                 }
#             }
#         }
#     }
# }
