#!/usr/bin/bash

set -eu

for config_file in ~/dotfiles/vimspector/*; do
  file_basename=${config_file##*/}
  filetype=${file_basename%%.*}
  vimspector_link_dir="$HOME/.vim/plugged/vimspector/configurations/linux/$filetype"
  mkdir -p "$vimspector_link_dir"
  vimspector_link_file="$vimspector_link_dir/$file_basename"
  ln_cmd="ln -s $config_file $vimspector_link_dir/$file_basename"
  echo $ln_cmd
  eval $ln_cmd
done
