#!/bin/bash

SILENT=0
while getopts "s" arg; do
  case $arg in
    s) SILENT=1;
  esac
done

AUDIO_PARAMS=""
if [[ $SILENT = 1 ]]; then
  echo "Video only"
else
  echo "Video and audio"
  AUDIO_PARAMS="-ac 2 -codec:a mp2 -b:a 128k"
fi

screen_resolution=$(xdpyinfo | grep 'dimensions:' | sed 's_^.* \([0-9]*x[0-9]*\).*_\1_')
ffmpeg -f x11grab -framerate 24 -video_size $screen_resolution -i "$DISPLAY" -thread_queue_size 512 -f pulse -i default -vcodec libx264 "$AUDIO_PARAMS" "$1"

