#!/usr/bin/env bash
wget --output-document=- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release --codename --short) llvm-toolchain-$(lsb_release --codename --short) main"
sudo apt update
sudo apt install clang-format
