#!/usr/bin/env bash

# see https://www.adacore.com/download
wget https://community.download.adacore.com/v1/f3a99d283f7b3d07293b2e1d07de00e31e332325?filename=gnat-2021-20210519-x86_64-linux-bin -O gnat_installer

chmod +x gnat_installer
./gnat_installer

rm -f gnat_installer
