#!/usr/bin/env bash

sudo apt-get install -y x11vnc x11-xserver-utils
pip3 install virtscreen

# Note: don't do this! both of the installation methods recommended in the README fail
# see https://github.com/kbumsik/VirtScreen/issues/89
# wget https://github.com/kbumsik/VirtScreen/releases/download/0.3.1/virtscreen.deb
# sudo dpkg -i virtscreen.deb
