#!/usr/bin/env bash

custom_installers/get_ada_language_server
custom_installers/get_clangd
sudo npm i -g bash-language-server
yarn global add vim-language-server
# sudo npm -i -g pyright
pip3 install 'python-lsp-server[all]'
custom_installers/get_rust-analyzer
go install github.com/mattn/efm-langserver@latest
